version: 2.1
jobs:
  # this job uses the ubuntu 18.04 docker image so that we have both
  # clang-format-8+ and python3.7
  tests:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: install dependencies
          command: |
            apt-get update && apt-get install -y clang-format-8 python3.7 python3-venv python3.7-venv make
            ln -s /usr/bin/clang-format-8 /usr/bin/clang-format
            python3.7 -m venv venv
            . venv/bin/activate
            ./scripts/setup.sh

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            ./scripts/test.sh

workflows:
  version: 2.1
  qa:
    jobs:
      - tests
